[tool.ruff]
line-length = 120

[tool.ruff.lint]

ignore = [
  "E501", # Never enforce `E501` (line length violations), which can be trivial.
]
select = [
  "C", # Convention violations, like coding standards issues (PEP8)
  "E", # Errors that could cause exceptions or major functionality issues
  "F", # Flaws in type annotations
  "I", # Import-related linting issues
  "W", # Warnings for stylistic or minor programming issues
  "PL", # PyLint checks, including unused function variables
  "N", # Naming convention checks (PEP8)
  "D", # Docstring style checks, often based on Google's style guidelines
  "UP", # Checks for deprecated Python features that could be upgraded
  "FIX", # Reminder tags for TODOs and FIXMEs in the code
]
pydocstyle.convention = "google"


# Ignore import violations in all `__init__.py` files.
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402", "F401", "F403", "F811"]

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[tool.isort]
profile = "black"
lines_after_imports = 2