name: Verify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: '3.14'
  CODE_DIRECTORY: './'
  REVIEWDOG_REPORTER: 'github-pr-review'
  REVIEWDOG_LEVEL: 'info'

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  mypy:
    runs-on: ubuntu-latest
    env:
      OUTPUT_FILE: mypy.txt

    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
            python-version: ${{ env.PYTHON_VERSION }}
            cache: 'pip' # caching pip dependencies

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install mypy
        run: pip install mypy

      - name: Set up reviewdog CLI
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: MyPy install types
        run: |
          mypy --install-types

      - name: Run mypy (print and save to file)
        shell: bash
        run: |
          python -m mypy --show-column-numbers --show-error-codes --disallow-untyped-defs --check-untyped-defs --namespace-packages --explicit-package-bases ${{ env.CODE_DIRECTORY }} > ${{ env.OUTPUT_FILE }} || true

      - name: Debug mypy output
        if: always()
        run: cat ${{ env.OUTPUT_FILE }}

      - name: Post mypy results with reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          cat ${{ env.OUTPUT_FILE }} | reviewdog -f=mypy -name="mypy" -reporter=${{ env.REVIEWDOG_REPORTER }} -level=${{ env.REVIEWDOG_LEVEL }}
  ruff:
    runs-on: ubuntu-latest
    name: Lint with Ruff
    env:
      OUTPUT_FILE: ruff.txt
    steps:
    - name: Check out code
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
  
    - name: Install ruff
      run: |
        python -m pip install --upgrade pip
        pip install ruff

    - name: Set up reviewdog CLI
      uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest

    - name: Run ruff
      run: |
        ruff check ${{ env.CODE_DIRECTORY }} --output-format rdjson > ${{ env.OUTPUT_FILE }} || true

    - name: Debug ruff output
      if: always()
      run: cat ${{ env.OUTPUT_FILE }}

    - name: Post ruff results with reviewdog
      if: always()
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: |
        cat ${{ env.OUTPUT_FILE }} | reviewdog -f=rdjson -name="ruff" -reporter=${{ env.REVIEWDOG_REPORTER }} -level=${{ env.REVIEWDOG_LEVEL }}
        
    