name: Verify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: '3.14'
  CODE_DIRECTORY: './'

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
            python-version: ${{ env.PYTHON_VERSION }}
            cache: 'pip' # caching pip dependencies

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install mypy
        run: pip install mypy

      - name: Set up reviewdog CLI
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Run mypy (print and save to file)
        shell: bash
        run: |
          python -m mypy --show-column-numbers --show-error-codes --disallow-untyped-defs --namespace-packages --explicit-package-bases > mypy.txt || true
          cat mypy.txt

      - name: Post mypy results with reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          cat mypy.txt | reviewdog -f=mypy -name="mypy" -reporter=github-pr-review -level=warning || true
  ruff:
    runs-on: ubuntu-latest
    name: Lint with Ruff
    steps:
    - name: Check out code
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
  
    - name: Install ruff
      run: |
        python -m pip install --upgrade pip
        pip install ruff
    - name: Set up reviewdog CLI
      uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest

    - name: Run ruff
      run: |
        ruff check ${{ env.CODE_DIRECTORY }} --format=rdjson 2>&1 > ruff.json
        cat ruff.json
    - name: Post ruff results with reviewdog
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: |
        cat ruff.json | reviewdog -f=ruff -name="ruff" -reporter=github-pr-review -level=warning || true
    